#!/usr/bin/env bash

VENV_PATH=$(eval "find ~/venvs -mindepth 1 -maxdepth 1 -type d"\
    | fzf)

if [[ -z $VENV_PATH ]]; then
    echo "No source path selected"
    exit 0
fi

source "$VENV_PATH"/bin/activate
